server:
  port: 3000  # Docker에서 매핑할 포트

spring:
  application:
    name: pednav
  datasource:
    url: jdbc:h2:mem:testdb  # Docker 환경에서는 메모리 DB 사용 권장
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          show_sql: true
          format_sql: true
          use_sql_comments: true
          default_batch_fetch_size: 1000
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: false  # H2 콘솔 비활성화 (Docker 환경에서는 보통 필요 없음)

logging:
  level:
    root: debug

management:
  endpoints:
    web:
      exposure:
        include: health, info

jmx:
  enabled: false
